"""empty message

Revision ID: 1e5ffb364d29
Revises: c6197b117d40
Create Date: 2023-11-23 11:00:07.485176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1e5ffb364d29'
down_revision: Union[str, None] = 'c6197b117d40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status_message', sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('status_message', 'message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status_message', sa.Column('message', sa.VARCHAR(), nullable=False))
    op.drop_column('status_message', 'content')
    # ### end Alembic commands ###
