"""empty message

Revision ID: c6197b117d40
Revises: 1f0503ef4312
Create Date: 2023-11-23 09:58:17.969590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c6197b117d40'
down_revision: Union[str, None] = '1f0503ef4312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status_message', sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('status_message', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status_message', sa.Column('content', sa.VARCHAR(), nullable=False))
    op.drop_column('status_message', 'message')
    # ### end Alembic commands ###
